### ISSUE TITLE
Pod install error OpenSSL-Apple

### ISSUE THREAD

**Issue by DonsWayo** [pia-foss/vpn-ios#6]
# Summary

### Steps to reproduce
(Please provide detail steps). 
cd repo
pod install

### What is the current bug behaviour?
(What actually happens).
[!] Error installing OpenSSL-Apple
[!] /usr/bin/git clone https://github.com/keeshux/OpenSSL-Apple /var/folders/sr/_bc9hcvx6211v60tyvtjcg_80000gp/T/d20190721-57906-1m78xko --template= --single-branch --depth 1 --branch 1.0

Cloning into '/var/folders/sr/_bc9hcvx6211v60tyvtjcg_80000gp/T/d20190721-57906-1m78xko'...
warning: Could not find remote branch 1.0 to clone.
fatal: Remote branch 1.0 not found in upstream origin

pod repo update not solve the problem

### What is the expected correct behaviour?
(What you should see instead).
pod install success
### Possible fixes suggested re-mediation
change branch?
### Assignees and labels
( please add labels as applicable )    

- [ ] Patched
- [ ] Verified patch

**Comment by patriksharma** [comment]
Same issue faced by me @DonsWayo , any solutions ?

**Comment by ueshiba** [comment]
Hello guys,

Sorry for the late reply!

The problem is compiling the openssl framework with the current version of Xcode and support old iOS SDK at the same time. (you need the iOS9 or iOS10 SDK installed in the computer).

If you change your min version to iOS 11 in the Podfile the problem will be fixed. If you want to keep iOS9 or iOS10, you must follow these steps:

Download Xcode 7 from Apple
Install Xcode 7 in Applications/xcode7
sudo xcode-select -switch /Applications/xcode7/Xcode.app/Contents/Developer
Clean all the pod cache from the computer
pod install ... etc
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
I hope this can help you guys!

Regards,
Jose.

**Comment by t0mmar** [comment]
I have a fork with a CI build that used to work with the above `xcode-select -switch` technique, but it started failing with the same error now - something changed:

```
Installing OpenSSL-Apple (1.1.0h)

[!] Error installing OpenSSL-Apple
[!] /usr/bin/git clone https://github.com/keeshux/OpenSSL-Apple /var/folders/sn/4mxh3x0539l67dvcp20s85sw0000gp/T/d20190731-82591-4nbnd1 --template= --single-branch --depth 1 --branch 1.0

Cloning into '/var/folders/sn/4mxh3x0539l67dvcp20s85sw0000gp/T/d20190731-82591-4nbnd1'...
warning: Could not find remote branch 1.0 to clone.
fatal: Remote branch 1.0 not found in upstream origin
```

Updating Podfile iOS to 11 works for 'pod install', but the project target 'PIA VPN' fails to build even after setting project iOS deployment target to ios11:

![image](https://user-images.githubusercontent.com/45108654/62251448-5f401b00-b3b5-11e9-86b0-5ff9e0c9d610.png)

**Comment by patriksharma** [comment]
@ueshiba Same error after changing the Pod targer version to IOS 11.0
![Screenshot 2019-08-01 at 9 45 19 AM](https://user-images.githubusercontent.com/383524/62265252-1f267a00-b441-11e9-89a1-0b65a51ea218.png)
 

```
[!] Error installing OpenSSL-Apple
[!] /usr/bin/git clone https://github.com/keeshux/OpenSSL-Apple /var/folders/r7/1435z4cj3t3cx1b3_nvl91vh0000gp/T/d20190801-27052-1bytqc --template= --single-branch --depth 1 --branch 1.0

Cloning into '/var/folders/r7/1435z4cj3t3cx1b3_nvl91vh0000gp/T/d20190801-27052-1bytqc'...
warning: Could not find remote branch 1.0 to clone.
fatal: Remote branch 1.0 not found in upstream origin
```

**Comment by patriksharma** [comment]
It looks like open SSL is not available in the repository anymore ?

**Comment by ueshiba** [comment]
Hi guys, the author of the OpenSSL-Apple project has set the min version to iOS11.

As a quick fix, we need to change the min version to iOS 11 and make this change in the Podfile:

`pod 'OpenSSL-Apple', '~> 1.1.0j.2'`

**Comment by t0mmar** [comment]
I don't see an explicit reference to OpenSSL-Apple in this project.  Is this change needed in the `tunnel-apple` project instead perhaps? Will someone from the PIA team update it?

https://github.com/pia-foss/tunnel-apple/blob/master/Podfile

**Comment by ueshiba** [comment]
Hi @t0mmar 

Yes, you need to change the tunnel-apple project. 

I pushed the changes to a release branch (https://github.com/pia-foss/tunnel-apple/tree/release/2.0.2). You can use the commit hash `d4b062d`.

Anyway you will need to update the min iOS version and set iOS11 in the this project and in the library if you are using it. 

Regards,
Jose.

**Comment by t0mmar** [comment]
Hmm, still not having much luck building the workspace itself :(

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/45108654/62314491-c4008180-b458-11e9-95ba-b305485efe2c.png">

**Comment by ueshiba** [comment]
Did you `pod cache clean 'OpenSSL-Apple' --all` before run the `pod install` again?

**Comment by t0mmar** [comment]
Thanks for the tip @ueshiba! I've tried that, cleared all the pods even, but I'm still getting the same set of errors.

**Comment by ueshiba** [comment]
Hello @t0mmar 

Can you update the PIATunnel commit to `8bc012a`?

Thanks

**Comment by t0mmar** [comment]
@ueshiba - I still get a few errors, but much less and different.  It sounds like they're related to the library.  Is there a new library commit hash that I should be using as well?

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/45108654/62559199-2930ea00-b840-11e9-94a4-4dbae6090df8.png">

**Comment by ueshiba** [comment]
@t0mmar Yes, the errors now are related with the PIALibrary (because you don't have the latest). The latest commit is `f88e06c` but this project is not going to compile because the PIAX code is not public yet... 

I hope to release the latest code very soon in the three projects, give me a couple of days.

Regards,
Jose

**Comment by trycatch007** [comment]
@ueshiba what's the status of these updates, still in progress?

**Comment by t0mmar** [comment]
@ueshiba - what's the status of these updates? still in progress?

**Comment by ueshiba** [comment]
I am still waiting to receive the approval to push the code and update the `develop` and `master` repo. Hopefully maybe today or tomorrow.

**Comment by t0mmar** [comment]
Thanks @ueshiba !

Just to verify, because I don't see any new commits to pia-foss/vpn-ios, the latest master should now work? With the following versions in the Podspec?

```
    library_by_git('12d542c')
    tunnel_by_git('4eff5ca')
```

**Comment by ueshiba** [comment]
@t0mmar take a look at this commit on the tunnel project

https://github.com/pia-foss/tunnel-apple/commit/8bc012aae23106c492a5f141fe85b25004b21d98

you should do the same in your custom implementation or use `tunnel_by_git('8bc012a')` and `library_by_git('78663b6')`

**Comment by ueshiba** [comment]
closing this issue because the problem is solved.
